/*
* Problem 2: Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

/*
* Mathematical Solution/ Explanation
* F(n) = F(n-1) +F(n-2)
*/

//Solution

var compute = function(n){
  var f0 = 2, f1 = 3, f2 = 5,temp;
  var sum =0;
  while(n>f0){
    sum +=f0;
    f0 = f1+f2;
    f1 = f2+f0;
    f2 = f0+f1;
  }
  return sum;
}
console.log(compute(4000000));
//sample results in console
